#!/usr/bin/env bash
# 语音秘书 TTS 运行时环境
# 用法：source scripts/voice_secretary_tts_env.sh

export COPAW_TTS_ENABLED="${COPAW_TTS_ENABLED:-1}"
export COPAW_TTS_PROVIDER="${COPAW_TTS_PROVIDER:-voxcpm2}"
export COPAW_TTS_VOICE="${COPAW_TTS_VOICE:-zh-CN-XiaoxiaoNeural}"
export COPAW_TTS_RATE="${COPAW_TTS_RATE:--8%}"
export COPAW_TTS_VOLUME="${COPAW_TTS_VOLUME:-+0%}"
export COPAW_TTS_PITCH="${COPAW_TTS_PITCH:-+0Hz}"
export COPAW_TTS_TIMEOUT_SECONDS="${COPAW_TTS_TIMEOUT_SECONDS:-30}"
export COPAW_TTS_MAX_CHARS="${COPAW_TTS_MAX_CHARS:-260}"

# VoxCPM2：可控语音克隆模式 — reference_wav 锁定音色 + 英文风格描述微调语调
export COPAW_TTS_VOXCPM_REPO_SRC_DIR="${COPAW_TTS_VOXCPM_REPO_SRC_DIR:-/home/featurize/work/aifscie/third_party/VoxCPM/src}"
export COPAW_TTS_VOXCPM_MODEL_DIR="${COPAW_TTS_VOXCPM_MODEL_DIR:-/home/featurize/work/ethan/models/VoxCPM2}"
export COPAW_TTS_VOXCPM_PROMPT_WAV="${COPAW_TTS_VOXCPM_PROMPT_WAV:-/home/featurize/work/aifscie/CoPaw/assets/voice_secretary/warm_female_secretary_prompt.wav}"
export COPAW_TTS_VOXCPM_PROMPT_TEXT="${COPAW_TTS_VOXCPM_PROMPT_TEXT:-您好，我是您的智能语音秘书，很高兴为您服务。接下来，我会用温柔、自然、清晰的声音，为您播报和提醒重要信息。}"
export COPAW_TTS_VOXCPM_REFERENCE_WAV="${COPAW_TTS_VOXCPM_REFERENCE_WAV:-}"
export COPAW_TTS_VOXCPM_USE_PROMPT_AS_REFERENCE="${COPAW_TTS_VOXCPM_USE_PROMPT_AS_REFERENCE:-1}"
export COPAW_TTS_VOXCPM_FORCE_STYLE_WITH_CONDITIONING="${COPAW_TTS_VOXCPM_FORCE_STYLE_WITH_CONDITIONING:-1}"
export COPAW_TTS_VOXCPM_STYLE="${COPAW_TTS_VOXCPM_STYLE:-A young woman, gentle and sweet voice, warm and professional secretary tone, speaking fluent Mandarin Chinese with clear articulation}"
export COPAW_TTS_VOXCPM_VOICE_LABEL="${COPAW_TTS_VOXCPM_VOICE_LABEL:-voxcpm2_secretary}"
export COPAW_TTS_VOXCPM_CFG_VALUE="${COPAW_TTS_VOXCPM_CFG_VALUE:-2.0}"
export COPAW_TTS_VOXCPM_INFERENCE_TIMESTEPS="${COPAW_TTS_VOXCPM_INFERENCE_TIMESTEPS:-10}"
export COPAW_TTS_VOXCPM_MAX_LEN="${COPAW_TTS_VOXCPM_MAX_LEN:-2048}"
export COPAW_TTS_VOXCPM_TIMEOUT_SECONDS="${COPAW_TTS_VOXCPM_TIMEOUT_SECONDS:-180}"
export COPAW_TTS_VOXCPM_OPTIMIZE="${COPAW_TTS_VOXCPM_OPTIMIZE:-0}"
export COPAW_TTS_VOXCPM_LOAD_DENOISER="${COPAW_TTS_VOXCPM_LOAD_DENOISER:-0}"
export COPAW_TTS_VOXCPM_NORMALIZE="${COPAW_TTS_VOXCPM_NORMALIZE:-0}"
export COPAW_TTS_VOXCPM_RETRY_BADCASE="${COPAW_TTS_VOXCPM_RETRY_BADCASE:-1}"
export COPAW_TTS_VOXCPM_DEVICE="${COPAW_TTS_VOXCPM_DEVICE:-cuda}"

# 兼容保留：如需临时切回浏览器/Edge TTS，可直接改 COPAW_TTS_PROVIDER。
unset COPAW_TTS_COSYVOICE_REPO_DIR COPAW_TTS_COSYVOICE_MODEL_DIR COPAW_TTS_COSYVOICE_VOICE \
  COPAW_TTS_COSYVOICE_SPEED COPAW_TTS_COSYVOICE_TEXT_FRONTEND COPAW_TTS_COSYVOICE_TIMEOUT_SECONDS \
  COPAW_TTS_FUN_COSYVOICE3_MODEL_DIR COPAW_TTS_FUN_COSYVOICE3_MODE COPAW_TTS_FUN_COSYVOICE3_PROMPT_WAV \
  COPAW_TTS_FUN_COSYVOICE3_PROMPT_TEXT COPAW_TTS_FUN_COSYVOICE3_INSTRUCT_TEXT COPAW_TTS_FUN_COSYVOICE3_VOICE \
  COPAW_TTS_FUN_COSYVOICE3_SPEED COPAW_TTS_FUN_COSYVOICE3_TEXT_FRONTEND COSYVOICE_DISABLE_WETEXT
